server:
  port: 8080
spring:
  application:
    name: "user-api"
  datasource:
    url: "jdbc:mysql://localhost:3306/blog_db"
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
jwt:
  secret: "${JWT_SECRET:5367566859703373367639792F423F452848284D6251655468576D5A71347437}"
logging:
  level:
    org:
      springframework.security: TRACE